name: Test and Release

on:
  push:
  workflow_dispatch:

jobs:
  tests-and-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      # Source
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Keep npm cache around to speed up installs
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

      - name: Check if source code is properly formatted
        run: npx prettier -c ./

      # Build
      - name: Install dependencies
        run: npm ci

      # Test
      - name: Compile TypeScript
        run: npx tsc

      - name: Run unit tests
        run: npm test

      - name: Run example
        run: npx tsx src/example.ts

      # Delivery (or deploy)
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
